export const SIGNUP_USER_BEGIN = "SIGNUP_USER_BEGIN" 
export const SIGNUP_USER_SUCCESS ="SIGNUP_USER_SUCCESS" 
export const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR" 

export const SIGNIN_USER_BEGIN = "SIGNIN_USER_BEGIN"
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS" 
export const SIGNIN_USER_ERROR = "SIGNIN_USER_ERROR" 
export const LOGOUT_USER = "LOGOUT_USER";